In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('/content/customer.csv')

In [8]:
df.sample(5)

    age  gender review education purchased
26   53  Female   Poor        PG        No
48   39  Female   Good        UG       Yes
31   22  Female   Poor    School       Yes
16   59    Male   Poor        UG       Yes
23   96  Female   Good    School        No

review and education : Ordinal
Purchased : label encoding

In [9]:
df = df.iloc[:,2:]

In [10]:
df.sample(5)

   review education purchased
45   Poor        PG       Yes
3    Good        PG        No
33   Good        PG       Yes
22   Poor        PG       Yes
49   Good        UG        No

In [11]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=.2,random_state =42)

In [12]:
X_train.shape , X_test.shape

((40, 2), (10, 2))

In [14]:
X_train.head(3)

     review education
12     Poor    School
4   Average        UG
37  Average        PG

In [15]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [16]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [17]:
X_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [19]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [22]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [23]:
y_train=le.transform(y_train)
y_test = le.transform(y_test)

In [24]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])