In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer , SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import  accuracy_score

In [ ]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [ ]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [ ]:
df.isnull().sum()

Age         177
Pclass        0
Fare          0
Survived      0
dtype: int64

In [ ]:
X = df.drop(columns=['Survived'])
y = df['Survived']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train

      Age  Pclass      Fare
331  45.5       1   28.5000
733  23.0       2   13.0000
382  32.0       3    7.9250
704  26.0       3    7.8542
813   6.0       3   31.2750
..    ...     ...       ...
106  21.0       3    7.6500
270   NaN       1   31.0000
860  41.0       3   14.1083
435  14.0       1  120.0000
102  21.0       1   77.2875

[712 rows x 3 columns]

In [ ]:
knn = KNNImputer(n_neighbors=12,weights='uniform')
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

weights = 'uniform' or 'distance'

In [ ]:
lr = LogisticRegression()
lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)
accuracy_score(y_test,y_pred)

0.7486033519553073

In [ ]:
si = SimpleImputer()
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [ ]:
lr = LogisticRegression()
lr.fit(X_train_trf2,y_train)

y_pred = lr.predict(X_test_trf2)
accuracy_score(y_test,y_pred)

0.7374301675977654